# Generated by Django 2.2 on 2019-02-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mom_first_name', models.CharField(max_length=40)),
                ('mom_last_name', models.CharField(max_length=40)),
                ('mom_phone_number', models.IntegerField(default='000-000-0000')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=40)),
                ('child_last_name', models.CharField(max_length=40)),
                ('child_mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models4App.Mom')),
            ],
        ),
    ]
